ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'MARKED_AWAITING_SIGNATURE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'STAGE_UNDONE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'CONTRACT_EDITED';
